server.port=9526
spring.application.name=springboot-application
config.codigo=123456
config.usuario = eduardock
config.mensaje = hola a todos
config.valores = saludos, alumnos, de, springboot

mi.proyecto.nombre = Springboot
mi.universidad = Instituto Tecnologico de Oaxaca
mi.carrera = Ingenieria en Sistemas Computacionales